language: go
go:
- 1.2
- 1.3
- 1.4
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get golang.org/x/tools/cmd/cover
- go get .

script:
- go test -v -coverprofile=cover.out || go test -v
