clone_folder: c:\projects\go\src\github.com\tus\tusd

environment:
  GOPATH: c:\projects\go
  GO15VENDOREXPERIMENT: 1

install:
  - git submodule update --init --recursive

build_script:
  - go env
  - go version

test_script:
  - go test -v .
  - go test -v ./filestore
  - go test -v ./limitedstore
  - go test -v ./memorylicker
  - go test -v ./s3store
