clone_folder: c:\projects\go\src\github.com\tus\tusd

environment:
  GOPATH: c:\projects\go
  GO15VENDOREXPERIMENT: 1

install:
  - git submodule update --init --recursive

build_script:
  - go env
  - go version
  - go get ./s3store
  - go get ./consullocker

test_script:
  - go test .
  - go test ./filestore
  - go test ./limitedstore
  - go test ./memorylocker
  - go test ./consullocker
  - go test ./s3store
