apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tusd
  namespace: tus
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: NFS_SERVER_IP
    path: "/"
